version: "3.9"
services:
    db:
        image: mysql:5.7
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3306:3306"
        environment:
            MYSQL_HOST_IP:
            MYSQL_ROOT_USER:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: employeedb
            MYSQL_USER:
            MYSQL_PASSWORD: